package io.demo.model;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Sentencia of the Poder Judicial de Santa Fe (PJSF), parsed from
 * https://portal.justiciasantafe.gov.ar/bdj/
 *
 * The {@link PJSFSumario} list is not a mapped class: it is generated by
 * parsing the text and stored as part of the sentencia (jsonb column).
 */
@JsonInclude(Include.NON_NULL)
@Entity
@Table(name = "sentencia")
@Getter
@Setter
@NoArgsConstructor
public class PJSFSentencia extends DemoDBObject {

	/** the PJSF document id (sid) used to retrieve the document from the web */
	@Column(name = "documentoId", unique = true)
	private String documentoId;

	@Column(name = "caratula", length = 2048)
	private String caratula;

	@Column(name = "tribunal")
	private String tribunal;

	@Column(name = "fecha")
	private OffsetDateTime fecha;

	@Column(name = "jueces", length = 2048)
	private String jueces;

	@Column(name = "fuente")
	private String fuente;

	@Column(name = "expediente")
	private String expediente;

	@Column(name = "anioCausa")
	private String anioCausa;

	@Column(name = "tomoAnio")
	private String tomoAnio;

	@Column(name = "paginaInicio")
	private String paginaInicio;

	@Column(name = "paginaFin")
	private String paginaFin;

	@Column(name = "resolucion")
	private String resolucion;

	@Column(name = "cita")
	private String cita;

	@Column(name = "saij")
	private String saij;

	@Column(name = "cuij")
	private String cuij;

	@Column(name = "tribunalOrigen", length = 1024)
	private String tribunalOrigen;

	@Column(name = "tribunalAnterior", length = 1024)
	private String tribunalAnterior;

	/** other metadata parsed from the web document */
	@JdbcTypeCode(SqlTypes.JSON)
	@Column(name = "metadata", columnDefinition = "jsonb")
	private Map<String, String> metadata = new HashMap<>();

	/** full text of the fallo */
	@Column(name = "texto", columnDefinition = "text")
	private String texto;

	/**
	 * the list of sumarios associated with this sentencia. Note that
	 * {@link PJSFSumario} is not a mapped class: it is stored as jsonb.
	 */
	@JdbcTypeCode(SqlTypes.JSON)
	@Column(name = "sumarios", columnDefinition = "jsonb")
	private List<PJSFSumario> sumarios = new ArrayList<>();

}