id=Id
query=Consulta
duration=Duraci\u00f3n
last-modified=\u00daltima modificaci\u00f3n
user=Usuario
open-results=Abrir resultados (JSON)


dateRange=Período
subject=Materia
reasoningEffort=Nivel de análisis
