search=Search
text=CONSULTA

dateRange=Per\u00edodo
subject=Materia
maxResults=M\u00e1x.
reasoningEffort=Nivel de análisis 
rag-not-available=El servidor de b\u00fasqueda no est\u00e1 disponible en este momento. Solamente pueden ejecutarse las 'consultas recientes' 

submit=Buscar 
submitted-ok=submitted successfully



