
brand=PODER JUDICIAL DE SANTA FE
app=ANTECEDENTES JURIDICOS



forgot-instructions= Por favor ingrese su email / nombre de usuario / teléfono registrado en el sistema<br/> y le enviaremos un correo electrónico con las instrucciones.
username-email-phone=Correo / Nombre de usuario / Teléfono
send=Enviar
go-to-signin=Ir a página de ingresar

enter-username-email-phone=Por favor ingrese su correo / nombre de usuario / teléfono

email-sent=Le enviamos un correo electrónico con las instrucciones para restablecer su contraseña
no-user-found=No hamos encontrado un usuario con el correo / nombre de usuario / teléfono proporcionado

no-email-associated=No hay correo electrónico asociado con este usuario

password-reset-subject=Reinicialer contraseña
