
brand=PODER JUDICIAL DE SANTA FE
app=ANTECEDENTES JURIDICOS


username-email-phone=Usuario / Email / Teléfono
password=Contraseña
signin=Ingresar
forgot-password=Olvidó su contraseña ? 
username-password-invalid=Credenciales inválidas
