brand=PODER JUDICIAL DE SANTA FE
app=ANTECEDENTES JURIDICOS

password-reset=Restablecer contrase\u00f1a

invalidtoken=El enlace de restablecimiento de contrase\u00f1a no es v\u00e1lido. Por favor solicite uno nuevo desde la p\u00e1gina de olvido de contrase\u00f1a.
expiredtoken=El enlace de restablecimiento de contrase\u00f1a ha expirado. Por favor solicite uno nuevo desde la p\u00e1gina de olvido de contrase\u00f1a.
