username=Usuario
new-password=Nueva contrase\u00f1a
email=Email
notice=Por favor ingrese la nueva contrase\u00f1a para <b>{0}</b> ( {1} )
submit=Guardar
signin=Ir a p\u00e1gina de ingresar
enter-password=Debe ingresar la nueva contrase\u00f1a
password-reset-success=La contrase\u00f1a fue restablecida correctamente. Ya puede ingresar con su nueva contrase\u00f1a.
